title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://yuwei-cao-git.github.io/biodataset

aux_links:
  Template Repository: https://yuwei-cao-git.com/biodataset
